# This example requires the 'crewai' and 'crewai_tools' libraries to be installed:
# pip install crewai crewai_tools

from crewai import Agent, Task, Crew, Process
from crewai_tools import SerperDevTool # Tool for searching the internet
# Import a default LLM
from langchain_community.llms import OpenAI

# --- 1. Define the Tools ---
# Initialize the tool for internet searching
# NOTE: This requires a SERPER_API_KEY environment variable to be set.
search_tool = SerperDevTool()

# --- 2. Define the Agents (The Crew Members) ---

# The Researcher Agent: Focuses on gathering factual, up-to-date data.
researcher = Agent(
    role='Senior Research Analyst',
    goal='Identify and summarize the latest trends and statistics in the space economy.',
    backstory='You are an expert market researcher with a knack for finding the most current and relevant data on emerging industries.',
    verbose=True, # Show the agent's thought process
    allow_delegation=False, # This agent executes its task directly
    tools=[search_tool],
    # Provide a default LLM
    llm=OpenAI(model="gpt-3.5-turbo-instruct")
)

# The Writer Agent: Focuses on turning raw data into polished, engaging content.
writer = Agent(
    role='Professional Content Writer',
    goal='Write a compelling and easy-to-read 4-paragraph article based on the research summary.',
    backstory='You are a skilled content strategist who can take complex data and transform it into engaging, accessible, and high-quality content for a general audience.',
    verbose=True,
    allow_delegation=False,
    # Provide a default LLM
    llm=OpenAI(model="gpt-3.5-turbo-instruct")
)

# --- 3. Define the Tasks (The Workload) ---

# Task 1: Research. Output is passed to Task 2.
research_task = Task(
    description='Conduct a thorough search for the top 3 global trends defining the space economy in 2025. Summarize the findings in bullet points, including sources and key statistics.',
    expected_output='A concise, detailed bulleted list summary of 3 key space economy trends, complete with statistics.',
    agent=researcher,
)

# Task 2: Writing. This task takes the result of Task 1 as context.
writing_task = Task(
    description='Using the research summary provided, write a 4-paragraph article introducing the space economy and detailing the three trends identified. The article should be engaging and professional.',
    expected_output='A final, polished 4-paragraph article.',
    agent=writer,
    # The context argument automatically injects the output of research_task
    context=[research_task]
)

# --- 4. Form the Crew and Run the Process ---

# The Crew orchestrates the agents and tasks.
project_crew = Crew(
    agents=[researcher, writer],
    tasks=[research_task, writing_task],
    # Sequential process means tasks run one after the other in the order defined
    process=Process.sequential,
    verbose=2 # Show detailed execution log
)

print("### Starting the Space Economy Article Crew ###")
# Kick off the defined workflow
result = project_crew.kickoff()

print("\n\n########################################")
print("## Final Article Generated by the Crew ##")
print("########################################")
print(result)
